import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { SyntheticEvent, useEffect, useState } from 'react'
import {CopyToClipboard} from 'react-copy-to-clipboard';
import styles from '../styles/Home.module.css'
import { Output, OutputResponse } from './api/files'

const SERVER_LIVE = 'http://localhost:5500/';

const Home: NextPage = () => {
  const [folderPath, setFolderPath] = useState('');
  const [filePath, setFilePath] = useState('');
  const [isRunning, setIsRunning] = useState(false);
  const [output, setOutput] = useState<Output | null>(null);

  useEffect(() => {
    const path = localStorage.getItem('folderPath');
    if (path) {
      setFolderPath(path);
    }
  }, [])
  

  const handleSubmit = async (e: SyntheticEvent) => {
    e.preventDefault();
    if (isRunning) {
      return;
    }
    try {
      setIsRunning(true);
      const res: any = await axios.post('/api/files', {
        filePath, folderPath
      });
      if (res.data as OutputResponse) {
        setOutput(res.data.response);
        localStorage.setItem('folderPath', folderPath);
      }
    } catch (error) {
      alert(JSON.stringify(error, null, 2));
    }
    setIsRunning(false);
  }

  const handleOpen = async () => {
    if (output?.coveragePath) {
      try {
        const res: any = await axios.post('/api/coverage', {
          filePath: output.coveragePath
        });
      } catch (error) {
        alert(JSON.stringify(error, null, 2));
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>IPTS Testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          IPTS Testing
        </h1>

        <div className="card my-4">
          <form onSubmit={handleSubmit}>
            <div className='ma-4'>
              <label className="label" htmlFor="folderPath">Folder path</label>
              <input className="input is-primary" type="text" name='folderPath' value={folderPath} required onChange={(e) => setFolderPath(e.target.value)} />
            </div>
            <div className='ma-4'>
              <label className="label" htmlFor="filePath">File path</label>
              <input className="input is-primary" type="text" name='filePath' value={filePath} required onChange={(e) => setFilePath(e.target.value)} />
            </div>
            <div className='is-flex'>
              <div className='ma-4'>
                <button className='button is-dark' type='submit' disabled={isRunning}>Find</button>
              </div>
              <div className='ma-4'>
                <button className='button is-danger' type='button' onClick={() => setFilePath('')} disabled={isRunning}>Clear</button>
              </div>
            </div>

          </form>
        </div>

        <div className='card'>
          <header className="card-header">
            <p className="card-header-title">
              OUTPUT
            </p>
          </header>
          <label className="label ml-4 mt-4">Test file</label>
          <div className={styles.field}>
            <input className="input is-info" type="text" readOnly value={output?.filePath} />
            <CopyToClipboard text={output ? output.filePath : ''}>
              <button className='button is-info'>Copy</button>
            </CopyToClipboard>
          </div>

          <label className="label ml-4">Coverage file</label>
          <div className={styles.field}>
            <input className="input is-info" type="text" readOnly value={output?.coveragePath} />
            <CopyToClipboard text={output ? output.coveragePath : ''}>
              <button className='button is-info'>Copy</button>
            </CopyToClipboard>
            {/* <button className='button is-info' onClick={handleOpen}>Open</button> */}
          </div>

          {output?.coveragePath &&
            <div className={styles.field}>
              <button className='button is-link'>
                <a href={SERVER_LIVE.concat(output.coveragePath)} target="_blank" rel="noreferrer">Open the coverage file on new tab</a>
              </button>
            </div>
          }

        </div>

      </main>

      <footer className={styles.footer}>
      Powered by Hoang Doan
      </footer>
    </div>
  )
}

export default Home
